apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: istiod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"

spec:
  project: default

  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      chart: istiod
      targetRevision: 1.30.3
      helm:
        valueFiles:
          - $values/infrastructure/istio/istiod/values.yaml

    - repoURL: https://github.com/rahulkishorparida/platform-infra.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jqPathExpressions:
        - .webhooks[]?.failurePolicy 

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
# Ignore differences in this field.
#   alues.yaml
# validationFailurePolicy: Fail
#         │
# Desired Istio configuration

# Argo CD
# ignoreDifferences
#         │
# Don't reconcile failurePolicy differences

# Istio
#   │
# May manage/change the live webhook failurePolicy