apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sigstore-policy-controller
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://sigstore.github.io/helm-charts
    chart: policy-controller
    targetRevision: 0.10.8

  destination:
    server: https://kubernetes.default.svc
    namespace: cosign-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true